struct PDStatusMessage {
	unsigned long long timestamp;
	short state;
	boolean estop;
	double current[8];
	
	unsigned long tickcount;
	unsigned long flags;

	double current16;
	double voltage16;
	double current32;
	double voltage32;
};

