enum WorkerStateCode {
	WORKERSTATECODE_ACTIVE,
	WORKERSTATECODE_STANDBY,
	WORKERSTATECODE_ERROR
};

struct StateMessage {
	WorkerStateCode code;
	string msg;
};

struct WorkerStateMessage {
	string worker; //@key
	StateMessage state;
};

