#pragma once



#define		MIL_OBJECTID_NO_OBJECT   0

// SHOOTERS
#define		MIL_OBJECTID_SHOOTERWINDOW_RED_LARGE  1
#define		MIL_OBJECTID_SHOOTERWINDOW_RED_SMALL  2
#define		MIL_OBJECTID_SHOOTERWINDOW_BLUE_LARGE  3
#define		MIL_OBJECTID_SHOOTERWINDOW_BLUE_SMALL  4

// BUOYS
#define		MIL_OBJECTID_BUOY_YELLOW   5
#define		MIL_OBJECTID_BUOY_RED   6
#define		MIL_OBJECTID_BUOY_GREEN   7

// PIPE
#define		MIL_OBJECTID_PIPE   8
//#define		MIL_OBJECTID_PIPES	9

// BINS
#define		MIL_OBJECTID_BIN_ALL   10
#define		MIL_OBJECTID_BIN_SHAPE   11
#define		MIL_OBJECTID_BIN_X   12
#define		MIL_OBJECTID_BIN_O   13
#define		MIL_OBJECTID_BIN_SINGLE   14
//#define		MIL_OBJECTID_BIN_SMALL_O   15

// TUBE
#define		MIL_OBJECTID_TUBE   16

// GATES
#define		MIL_OBJECTID_GATE_VALIDATION   17
#define		MIL_OBJECTID_GATE_HEDGE   18

// HYDROPHONES
#define		MIL_OBJECTID_HYDROPHONE   19

// COLOR CALIBRATION
#define		MIL_OBJECTID_COLORCALIBRATION	20

// VELOCITY RANGE ESTIMATION
#define		MIL_OBJECTID_VELOCITY_RANGE_ESTIMATION	21
#define		MIL_OBJECTID_BEACON_TEST	22
